apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
  namespace: karpenter
spec:
  limits:
  - default: {}
    defaultRequest:
      cpu: 10m
      memory: 128Mi
    type: Container
