apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
  namespace: redis
spec:
  limits:
  - default:
      memory: 2Gi
    defaultRequest:
      cpu: 10m
      memory: 128Mi
    type: Container
