apiVersion: batch/v1
kind: CronJob
metadata:
  name: notification-scheduled-batch
  namespace: sns
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 2
      ttlSecondsAfterFinished: 120
      template:
        spec:
          containers:
            - name: notification-worker
              image: jheo/notification-batch:1.0.0
              env:
              - name: SPRING_PROFILES_ACTIVE
                value: dev
              - name: MYSQL_HOST: 
                value: "mysql.infra.svc.cluster.local"
              - name: MYSQL_PORT:
                value: "3306"
              envFrom:
              - secretRef:
                  name: mysql-secret
              - configMapRef:
                  name: email-config
              - secretRef:
                  name: email-secret
          restartPolicy: Never