image:
  repository: 516696002612.dkr.ecr.ap-northeast-2.amazonaws.com/feed-server # Private registry 입니다. public registry는 jheo/feed-server 입니다.
  pullPolicy: Always
  tag: "1.0.0" # 이미지 태그를 지정합니다.

envs: 
  SPRING_PROFILES_ACTIVE: dev
  USER_SERVICE: user-service
  KAFKA_HOST: "kafka.kafka.svc.cluster.local"
  KAFKA_PORT: "9092"
  KAFKA_SASL_PROTOCOL: "SASL_PLAINTEXT"
  KAFKA_SASL_MECHANISM: "PLAIN"
  MYSQL_HOST: "mysql.infra.svc.cluster.local"
  MYSQL_PORT: "3306"

# Replica count
replicaCount: 2

# HPA
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Networking
container:
  port: 8080

# Volume
pvc:
  enabled: false
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-sc"
  size: 10Gi

terminationGracePeriodSeconds: 30

metrics:
  enabled: false # 메트릭을 사용할지 결정합니다
  path: /metrics # 메트릭 경로를 지정합니다.

probes:
  liveness:
    enabled: false
    path: /healthcheck/live # liveness 경로를 바꿀 수 있습니다 e.g. /healthz
  readiness:
    enabled: false
    path: /healthcheck/ready # readiness 경로를 바꿀 수 있습니다 e.g. /healthz

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Authentication
serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

# Security
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 2000
  fsGroup: 3000

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []

# Conatiner resources
resources:
  limits:
    # memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

# Scheduling
nodeSelector: {}
tolerations: []
affinity: {}

# tolerations:
# - effect: NoSchedule
#   key: node
#   operator: Equal
#   value: service
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: node
#           operator: In
#           values:
#           - service
