apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-podmonitor
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      targetPort: 9404
      scheme: http
  selector:
    matchLabels:
      strimzi.io/kind: Kafka