apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configmap
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: configMap
    repoURL: https://github.com/Fastcampus-Kubernetes-Devops/Part_7.git
    targetRevision: HEAD
