apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployments
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: sns
  project: default
  source:
    path: deployments
    repoURL: https://github.com/Fastcampus-Kubernetes-Devops/Part_7.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
