apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: service
spec:
  template:
    metadata:
      labels:
        node: service
    spec:
      nodeClassRef:
        name: default
      taints:
      - effect: NoSchedule
        key: node
        value: service
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["5"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-northeast-2a"]
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  limits:
    cpu: 1000
