apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: multiaz
spec:
  template:
    metadata:
      labels:
        node: multiaz
    spec:
      nodeClassRef:
        name: default
      taints:
      - effect: NoSchedule
        key: node
        value: multiaz
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        # - key: "karpenter.k8s.aws/instance-cpu"
        #   operator: In
        #   values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["5"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30d
  limits:
    cpu: 1000
