defaultRules:
  create: true
  rules:
    etcd: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    windows: false

## Configuration for alertmanager
alertmanager:
  enabled: true
  # config:
  #   route:
  #     group_by: ['namespace']
  #     group_wait: 30s
  #     group_interval: 2m
  #     repeat_interval: 6h
  #     receiver: 'slack-notifications'
  #     routes:
  #     - receiver: 'slack-notifications'
  #       matchers:
  #         - alertname =~ "InfoInhibitor|Watchdog"
  #   receivers:
  #   - name: 'slack-notifications'
  #     slack_configs:
  #     - api_url: "{{ SLACK_API }}" # 여기에 Slack Webhook URL을 넣습니다.
  #       channel: '#alert-grafana-jerry-test' # 메시지를 보낼 Slack 채널
  #       send_resolved: true
  #       title: '{{ template "slack.default.title" . }}'
  #       text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"

grafana:
  enabled: true
  defaultDashboardsTimezone: Asia/Seoul
  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing # internet-facing or internal
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: sg-external
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/success-codes: 200-302
      alb.ingress.kubernetes.io/certificate-arn: "{{ CERT_ARN }}"
      external-dns.alpha.kubernetes.io/hostname: grafana.jerryljh.me
    hosts:
    - grafana.jerryljh.me
    paths:
    - /*
  persistence:
    type: pvc
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 5Gi
    finalizers:
    - kubernetes.io/pvc-protection

  # Provision grafana-dashboards-kubernetes
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'grafana-dashboards-kubernetes'
        orgId: 1
        folder: 'Kubernetes'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes

  dashboards:
    grafana-dashboards-kubernetes:
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ''
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ''
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ''
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ''

kubeApiServer:
  enabled: false
kubelet:
  enabled: true
kubeControllerManager:
  enabled: false
coreDns:
  enabled: true
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: true
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
prometheusOperator:
  enabled: true

prometheus-node-exporter:
  priorityClassName: system-node-critical

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 5d
    retentionSize: 10GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
