apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis
  endpoints:
  - port: http-metrics
    interval: 30s
